# Generated by Django 3.2.5 on 2022-01-28 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('all', 'All'), ('arts', 'Arts'), ('automotive', 'Automotive'), ('baby', 'Baby'), ('beauty', 'Beauty'), ('books', 'Books'), ('boys', "Boy's"), ('computers', 'Computers'), ('electronics', 'Electronics'), ('girls', "Girl's"), ('health', 'Health'), ('kitchen', 'Kitchen'), ('industrial', 'Industrial'), ('mens', "Men's"), ('pets', 'Pets'), ('sports', 'Sports'), ('games', 'Games'), ('travel', 'Travel'), ('womens', "Women's")], max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('visits', 'Visits'), ('search', 'Search'), ('clicks', 'Clicks')], max_length=16)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=16)),
                ('period_start', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
